# Generated by Django 4.2.3 on 2026-02-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_reset_password",
            field=models.BooleanField(default=False),
        ),
    ]
