# Generated by Django 6.0.1 on 2026-01-09 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='appointments.appointment')),
                ('doctor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='authored_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_own_record', 'Can view own medical record')],
            },
        ),
    ]
